name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout and Build
        env:
          MYSQL_DATABASE: yatter
          MYSQL_USER: yatter
          MYSQL_PASSWORD: yatter
          MYSQL_HOST: "mysql:3306"
        run: |
          docker compose up -d

      - name: Check
        run: docker container ls -a

      - name: Test
        run: docker compose exec -T web make test
